import type { Restaurant } from '@/src/types/models';

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: 'mock-1',
    name: 'Trattoria del Sole',
    photoUrl: null,
    rating: 4.5,
    priceLevel: 2,
    location: { lat: 48.8566, lng: 2.3522 },
    address: '12 rue de Rivoli, 75004 Paris',
    tags: ['italian', 'pizza', 'pasta'],
  },
  {
    id: 'mock-2',
    name: 'Sushi Zen',
    photoUrl: null,
    rating: 4.7,
    priceLevel: 3,
    location: { lat: 48.86, lng: 2.34 },
    address: '5 rue Saint-Honoré, 75001 Paris',
    tags: ['japanese', 'sushi'],
  },
  {
    id: 'mock-3',
    name: 'Le Petit Bistrot',
    photoUrl: null,
    rating: 4.2,
    priceLevel: 2,
    location: { lat: 48.853, lng: 2.349 },
    address: '22 rue des Archives, 75003 Paris',
    tags: ['french', 'bistro'],
  },
  {
    id: 'mock-4',
    name: 'Burger Factory',
    photoUrl: null,
    rating: 3.9,
    priceLevel: 1,
    location: { lat: 48.858, lng: 2.347 },
    address: '8 boulevard Sébastopol, 75004 Paris',
    tags: ['american', 'burger', 'fast food'],
  },
  {
    id: 'mock-5',
    name: 'Pho Hanoi',
    photoUrl: null,
    rating: 4.4,
    priceLevel: 1,
    location: { lat: 48.861, lng: 2.355 },
    address: '14 rue du Temple, 75004 Paris',
    tags: ['vietnamese', 'asian', 'pho'],
  },
  {
    id: 'mock-6',
    name: 'Tapas y Vino',
    photoUrl: null,
    rating: 4.1,
    priceLevel: 2,
    location: { lat: 48.855, lng: 2.351 },
    address: '7 rue Vieille du Temple, 75004 Paris',
    tags: ['spanish', 'tapas'],
  },
  {
    id: 'mock-7',
    name: 'Le Gourmet Étoilé',
    photoUrl: null,
    rating: 4.9,
    priceLevel: 4,
    location: { lat: 48.864, lng: 2.343 },
    address: '3 place des Vosges, 75004 Paris',
    tags: ['french', 'fine dining', 'gastronomic'],
  },
  {
    id: 'mock-8',
    name: 'Taco Loco',
    photoUrl: null,
    rating: 4.0,
    priceLevel: 1,
    location: { lat: 48.857, lng: 2.346 },
    address: '18 rue Quincampoix, 75004 Paris',
    tags: ['mexican', 'tacos'],
  },
  {
    id: 'mock-9',
    name: 'Curry Palace',
    photoUrl: null,
    rating: 4.3,
    priceLevel: 2,
    location: { lat: 48.859, lng: 2.353 },
    address: '11 rue de Bretagne, 75003 Paris',
    tags: ['indian', 'curry'],
  },
  {
    id: 'mock-10',
    name: 'Vegan Garden',
    photoUrl: null,
    rating: 4.6,
    priceLevel: 2,
    location: { lat: 48.862, lng: 2.348 },
    address: '9 rue Charlot, 75003 Paris',
    tags: ['vegan', 'vegetarian', 'healthy'],
  },
];
